library 'cb-days@master'
def testPodYaml = libraryResource 'podtemplates/vuejs/vuejs-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('VueJS Test and Build')
  {
    stage('VueJS Tests') {
      agent {
        kubernetes {
          label 'nodejs'
          yaml testPodYaml
       }
      }
      steps {
            checkout scm           
            container('nodejs') {
              sh '''
                 yarn install
                 yarn test:unit
                 '''
            }
      } 
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        imgBuildNexus("microblog-frontend", "${repoOwner}", "${registry}")
        {
          checkout scm
        }
      }
    }
    stage('Invoke ARO - Deploy to Prod') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps {
        cloudBeesFlowCallRestApi body: '{"pipelineParameter":[{"pipelineParameterName":"microblog-frontend_version","value":"1.0.6"},{"pipelineParameterName":"microblog-backend_version","value":"1.0.2"},{"pipelineParameterName":"microblog-db_version","value":"12.1-alpine"}]}',
        configuration: 'CB Flow', 
        envVarNameForResult: 'CALL_REST_API_CREATE_PROJECT_RESULT', 
        httpMethod: 'POST', 
        urlPath: '/releases?projectName=dtidwell%20Demo&releaseName=Blog%202020-04-30'
      }
    }
  }
}

