library 'cb-days@ff-demo'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('Build images')
  {
    stage('Build and Push Backend image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        imgBuildNexusGeneric("news-backend", "${username}", "${registry}", "news-backend")
        {
          checkout scm
        }
      }
    }
    stage('Build and Push Frontend image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        imgBuildNexusGeneric("news-frontend", "${username}", "${registry}", "news-frontend")
        {
          checkout scm
          sh "sed -i 's,REPLACE_BACKEND_URL,http://backend.${username}.cb-demos.io,g' news-frontend/.env"
          sh "sed -i 's,REPLACE_CB_FF_API_KEY,${cbffApiKey},g' news-frontend/.env"
        }
      }
    }  
  }
}

